Repository TypingOK/team-1, pull requests merged in 2024-02, with the labels that each got.

#27 Feat 디자인 card
  packages/design-kit/package.json
  packages/design-kit/public/CD/card_icon/Like.svg
  packages/design-kit/public/CD/card_icon/Seen.svg
  packages/design-kit/public/CD/card_icon/Vector.svg
  packages/design-kit/public/CD/pageList/Icon/btn 1/Line 101.svg
  packages/design-kit/public/CD/pageList/Icon/btn 1/Vector 653.svg
  packages/design-kit/public/CD/pageList/Icon/btn 4/Line 102.svg
  packages/design-kit/public/CD/pageList/Icon/btn 4/Vector 656.svg
  packages/design-kit/public/CD/pageList/Icon/next.svg
  packages/design-kit/public/CD/pageList/Icon/prev.svg
  packages/design-kit/public/images/Carousel_other1.png
  packages/design-kit/public/images/Carousel_other2.png
  packages/design-kit/public/images/Carousel_other3.png
  packages/design-kit/public/images/Carousel_sl1.png
  packages/design-kit/public/images/Carousel_sl2.png
  packages/design-kit/public/images/Carousel_sl3.png
  packages/design-kit/public/images/Log_main.png
  packages/design-kit/public/indicator-blue.svg
  packages/design-kit/public/indicator-gary.svg
  packages/design-kit/src/App.tsx
  packages/design-kit/src/components/badge/index.ts
  packages/design-kit/src/components/button/index.ts
  packages/design-kit/src/components/card/heroImage/HeroImage.tsx
  packages/design-kit/src/components/card/heroImage/HeroImageExample.tsx
  packages/design-kit/src/components/card/index.ts
  packages/design-kit/src/components/card/myCard/Example.tsx
  packages/design-kit/src/components/card/myCard/MyCard.tsx
  packages/design-kit/src/components/datepicker/index.ts
  packages/design-kit/src/components/dropDown/Example.tsx
  packages/design-kit/src/components/dropDown/index.ts
  packages/design-kit/src/components/indicator/Indicator.tsx
  packages/design-kit/src/components/indicator/index.ts
  packages/design-kit/src/components/pagination/index.ts
  packages/design-kit/src/components/select/index.ts
  packages/design-kit/src/components/swiper/Carousel.tsx
  packages/design-kit/src/components/swiper/Example.tsx
  packages/design-kit/src/components/swiper/ExampleRightSection.tsx
  packages/design-kit/src/components/swiper/index.ts
  packages/design-kit/src/index.ts
  packages/design-kit/src/utils/index.ts
  turbo.json
Labels: Pull request

#26 Feat: react-hook-form으로 회원가입 첫번째 페이지 구현
  apps/team-1/src/app/layout.tsx
  apps/team-1/src/app/login/page.tsx
  apps/team-1/src/app/signup/page.tsx
  apps/team-1/src/app/signup2/page.tsx
  apps/team-1/src/recoil/joinUserState.tsx
  apps/team-1/src/recoil/recoilRootWrapper.tsx
  apps/team-1/src/types/userTypes.ts
Labels: Feature

#28 Fix: package.json 누락
  apps/team-1/package.json
  yarn.lock
Labels: fix

#29 디자인 시스템 Input, TextArea, Card 추가
  apps/team-1/src/app/page.tsx
  packages/design-kit/package.json
  packages/design-kit/src/App.tsx
  packages/design-kit/src/components/Label/Label.tsx
  packages/design-kit/src/components/badge/Example.tsx
  packages/design-kit/src/components/button/Button.tsx
  packages/design-kit/src/components/button/Example.tsx
  packages/design-kit/src/components/card/heroImage/HeroImage.tsx
  packages/design-kit/src/components/card/heroImage/HeroImageExample.tsx
  packages/design-kit/src/components/card/myCard/Example.tsx
  packages/design-kit/src/components/card/myCard/MyCard.tsx
  packages/design-kit/src/components/datepicker/Example.tsx
  packages/design-kit/src/components/dropDown/Example.tsx
  packages/design-kit/src/components/input/Example.tsx
  packages/design-kit/src/components/input/Input.tsx
  packages/design-kit/src/components/input/index.ts
  packages/design-kit/src/components/select/Example.tsx
  packages/design-kit/src/components/swiper/Carousel.tsx
  packages/design-kit/src/components/swiper/Example.tsx
  packages/design-kit/src/components/swiper/ExampleRightSection.tsx
  packages/design-kit/src/components/tab/Example.tsx
  packages/design-kit/src/components/tab/Tab.tsx
  packages/design-kit/src/components/tab/index.ts
  packages/design-kit/src/components/textArea/Example.tsx
  packages/design-kit/src/components/textArea/TextArea.tsx
  packages/design-kit/src/components/textArea/index.ts
  packages/design-kit/src/index.ts
Labels: Pull request

#33 모달, 헤더, 푸터 작성
  apps/team-1/public/header/alert.svg
  apps/team-1/public/header/chatting.svg
  apps/team-1/public/header/darkmode.svg
  apps/team-1/public/header/down.svg
  apps/team-1/public/header/icons.png
  apps/team-1/public/header/search.svg
  apps/team-1/public/header/user-profile.svg
  apps/team-1/public/logo.svg
  apps/team-1/src/app/layout.tsx
  apps/team-1/src/components/footer/Footer.tsx
  apps/team-1/src/components/footer/FooterFamilySite.tsx
  apps/team-1/src/components/footer/FooterWrapper.tsx
  apps/team-1/src/components/header/Header.tsx
  apps/team-1/src/components/header/HeaderRight.tsx
  apps/team-1/src/components/header/HeaderWrapper.tsx
  package.json
  packages/design-kit/src/App.tsx
  packages/design-kit/src/components/Label/Label.tsx
  packages/design-kit/src/components/modal/Example.tsx
  packages/design-kit/src/components/modal/Modal.tsx
  packages/design-kit/src/components/modal/index.ts
  packages/design-kit/src/components/select/index.ts
  packages/design-kit/src/index.ts
Labels: Feature

#34 Feat: 글쓰기 페이지 작성
  apps/team-1/package.json
  apps/team-1/public/icons/create/Bold.svg
  apps/team-1/public/icons/create/Cancle.svg
  apps/team-1/public/icons/create/H1.svg
  apps/team-1/public/icons/create/H2.svg
  apps/team-1/public/icons/create/H3.svg
  apps/team-1/public/icons/create/H4.svg
  apps/team-1/public/icons/create/Italic.svg
  apps/team-1/public/icons/create/Underline.svg
  apps/team-1/public/icons/create/publish.svg
  apps/team-1/src/app/(components)/CustomEditor.tsx
  apps/team-1/src/app/(components)/CustomToolbar.tsx
  apps/team-1/src/app/logs/[logId]/(components)/CustomViewer.tsx
  apps/team-1/src/app/logs/create/(components)/CustomEditor.tsx
  apps/team-1/src/app/logs/create/(components)/CustomToolbar.tsx
  apps/team-1/src/app/logs/create/(components)/style.css
  apps/team-1/src/app/logs/create/page.tsx
  apps/team-1/src/components/footer/Footer.tsx
  apps/team-1/src/components/footer/FooterWrapper.tsx
  apps/team-1/src/components/header/HeaderWrapper.tsx
  packages/design-kit/src/components/modal/Modal.tsx
  yarn.lock
Labels: Feature

#40 Feat main page
  apps/team-1/src/app/(components)/(mainPage)/Swiper.tsx
  apps/team-1/src/app/(components)/(mainPage)/SwiperWrapper.tsx
  apps/team-1/src/app/api/route.ts
  apps/team-1/src/app/page.tsx
  apps/team-1/src/components/header/Header.tsx
  apps/team-1/src/components/header/HeaderRight.tsx
  apps/team-1/src/components/header/HeaderRightAuth.tsx
  apps/team-1/src/types/userTypes.ts
  packages/design-kit/src/components/badge/Badge.tsx
  packages/design-kit/src/components/badge/EditModeSVG.tsx
  packages/design-kit/src/components/card/heroImage/HeroImage.tsx
  packages/design-kit/src/components/dropDown/DropDown.tsx
  packages/design-kit/src/components/indicator/Indicator.tsx
Labels: Feature

#42 Feat: 로그인 페이지에서 로그인 돼었을 시 메인페이지로 리다이렉트
  apps/team-1/src/app/login/page.tsx
  apps/team-1/src/middleware.ts
  packages/design-kit/tailwind.config.js
Labels: Feature

#46 Feat main page
  apps/team-1/next.config.js
  apps/team-1/public/Main.png
  apps/team-1/public/eyes.png
  apps/team-1/public/fire.png
  apps/team-1/public/folder.png
  apps/team-1/public/leftBanner.png
  apps/team-1/public/rightBanner.png
  apps/team-1/src/app/(components)/(mainPage)/Community.tsx
  apps/team-1/src/app/(components)/(mainPage)/LogsSection.tsx
  apps/team-1/src/app/(components)/(mainPage)/ShortCut.tsx
  apps/team-1/src/app/(components)/(mainPage)/Swiper.tsx
  apps/team-1/src/app/layout.tsx
  apps/team-1/src/app/logs/page.tsx
  apps/team-1/src/app/page.tsx
  apps/team-1/src/components/header/Header.tsx
  apps/team-1/src/components/header/HeaderWrapper.tsx
  apps/team-1/src/components/logs/LogList.tsx
  apps/team-1/src/components/logs/LogTabs.tsx
  apps/team-1/src/hooks/queries/useGetLogLists.ts
  packages/design-kit/src/components/card/myCard/MyCard.tsx
  packages/design-kit/src/components/pagination/Pagination.tsx
  packages/design-kit/src/components/swiper/Carousel.tsx
Labels: Feature, Pull request

#47 Feat: detail page
  apps/team-1/next.config.js
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentContainer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentContentsContainer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentCustomViewer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentInput.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentInputContainer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentItem.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentProfileCard.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/ReplyCommentContainer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/style.css
  apps/team-1/src/app/logs/[logId]/(components)/CustomViewer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/FloatingMenu/FloatingMenu.tsx
  apps/team-1/src/app/logs/[logId]/(components)/LogCenterInfo.tsx
  apps/team-1/src/app/logs/[logId]/(components)/LogHeader.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Recommend/OwnerRecommendContainer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Recommend/RecommendCard.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Recommend/RecommendContainer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Recommend/RecommendProfile.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Recommend/TagRecommendContainer.tsx
  apps/team-1/src/app/logs/[logId]/page.tsx
  apps/team-1/src/hooks/queries/useCreateComment.ts
  apps/team-1/src/hooks/queries/useCreateReply.ts
  apps/team-1/src/hooks/queries/useGetComments.ts
  apps/team-1/src/hooks/queries/useGetLogDetail.ts
  apps/team-1/src/hooks/queries/useGetOwnerRecommendLogs.ts
  apps/team-1/src/hooks/queries/useGetTagRecommend.ts
  apps/team-1/src/types/logTypes.ts
  apps/team-1/src/types/replyCommentsTypes.ts
  apps/team-1/src/utils/api/logsApi.ts
  apps/team-1/src/utils/api/replyCommentApi.ts
  apps/team-1/src/utils/api/usersApi.ts
  apps/team-1/src/utils/common/formatDate.ts
  apps/team-1/src/utils/logs/getComments.ts
Labels: Feature

#45 Feat: 회원가입 최종
  apps/team-1/public/checkImage.svg
  apps/team-1/public/uncheckImage.svg
  apps/team-1/src/app/login/page.tsx
  apps/team-1/src/app/signup/page.tsx
  apps/team-1/src/components/signUpComplete.tsx
  apps/team-1/src/components/signUpSecond.tsx
  apps/team-1/src/components/signup/roundCheckbox.tsx
  apps/team-1/src/components/signup/signUpComplete.tsx
  apps/team-1/src/components/signup/signUpEmailVerify.tsx
  apps/team-1/src/components/signup/signUpFirst.tsx
  apps/team-1/src/components/signup/signUpSecond.tsx
  apps/team-1/src/components/signup/signUpStart.tsx
  apps/team-1/src/data/data.ts
  packages/design-kit/tailwind.config.js
Labels: Design

#49 Feat: seo 대응
  apps/team-1/src/app/logs/[logId]/layout.tsx
  apps/team-1/src/middleware.ts
Labels: Feature

#50 Feat: 프로필 클릭시 해당 유저의 마이페이지로 이동 및 다른 사람 로그보기 기능 수정
  apps/team-1/src/app/logs/[logId]/(components)/Comments/CommentProfileCard.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Comments/ReplyCommentContainer.tsx
  apps/team-1/src/app/logs/[logId]/(components)/LogHeader.tsx
  apps/team-1/src/app/logs/[logId]/(components)/Recommend/RecommendContainer.tsx
  apps/team-1/src/app/mypage/[username]/(components)/MyLogs.tsx
  apps/team-1/src/components/header/HeaderRight.tsx
  apps/team-1/src/hooks/queries/useGetMyLogs.ts
  apps/team-1/src/utils/api/logsApi.ts
Labels: Feature

#52 Feat: 마이페이지 수정
  apps/team-1/src/app/mypage/[username]/(components)/AdditionalProfile.tsx
  apps/team-1/src/app/mypage/[username]/(components)/MyArchive.tsx
  apps/team-1/src/app/mypage/[username]/(components)/MyLogs.tsx
  apps/team-1/src/app/mypage/[username]/myactive/(components)/MyLikesLog.tsx
  apps/team-1/src/app/mypage/[username]/myactive/(components)/MyViewsLog.tsx
  apps/team-1/src/hooks/queries/useGetMyArchive.ts
Labels: Feature

#53 Feat: 비밀번호 변경 이메일 보내기 구현
  apps/team-1/src/app/changePassword/page.tsx
  apps/team-1/src/app/login/page.tsx
  apps/team-1/src/components/changePassword/changePassword.tsx
  apps/team-1/src/components/changePassword/changePasswordComplete.tsx
  apps/team-1/src/utils/api/usersApi.ts
Labels: Feature
